//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_despesa
    {
        public decimal id { get; set; }
        public Nullable<decimal> id_documento { get; set; }
        public long id_cf_deputado { get; set; }
        public Nullable<long> id_cf_mandato { get; set; }
        public long id_cf_despesa_tipo { get; set; }
        public Nullable<long> id_cf_especificacao { get; set; }
        public Nullable<long> id_fornecedor { get; set; }
        public string nome_passageiro { get; set; }
        public string numero_documento { get; set; }
        public int tipo_documento { get; set; }
        public Nullable<System.DateTime> data_emissao { get; set; }
        public Nullable<decimal> valor_documento { get; set; }
        public decimal valor_glosa { get; set; }
        public decimal valor_liquido { get; set; }
        public Nullable<decimal> valor_restituicao { get; set; }
        public int mes { get; set; }
        public int ano { get; set; }
        public long parcela { get; set; }
        public string trecho_viagem { get; set; }
        public long lote { get; set; }
        public Nullable<long> ressarcimento { get; set; }
        public long ano_mes { get; set; }
    }
}
