//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_deputado
    {
        public int id { get; set; }
        public Nullable<int> id_cadastro { get; set; }
        public Nullable<int> id_parlamentar { get; set; }
        public Nullable<int> id_partido { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> cod_orcamento { get; set; }
        public string nome_parlamentar { get; set; }
        public string nome_civil { get; set; }
        public string condicao { get; set; }
        public string url_foto { get; set; }
        public string sexo { get; set; }
        public string gabinete { get; set; }
        public string anexo { get; set; }
        public string fone { get; set; }
        public string email { get; set; }
        public string profissao { get; set; }
        public Nullable<System.DateTime> nascimento { get; set; }
        public Nullable<System.DateTime> falecimento { get; set; }
        public Nullable<int> matricula { get; set; }
        public Nullable<decimal> valor_total_ceap { get; set; }
        public Nullable<sbyte> quantidade_secretarios { get; set; }
    }
}
