//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_sessao_camara
    {
        public int idSessao { get; set; }
        public int legislatura { get; set; }
        public string descricao { get; set; }
        public string inicio { get; set; }
        public System.DateTime dataSessao { get; set; }
    }
}
