//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class opsauditoriaEntities : DbContext
    {
        public opsauditoriaEntities()
            : base("name=opsauditoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cf_deputado> cf_deputado { get; set; }
        public virtual DbSet<cf_despesa> cf_despesa { get; set; }
        public virtual DbSet<cf_despesa_tipo> cf_despesa_tipo { get; set; }
        public virtual DbSet<cf_presenca_deputado> cf_presenca_deputado { get; set; }
        public virtual DbSet<cf_sessao_camara> cf_sessao_camara { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<fornecedor> fornecedors { get; set; }
        public virtual DbSet<fornecedor_info> fornecedor_info { get; set; }
        public virtual DbSet<fornecedor_natureza_juridica> fornecedor_natureza_juridica { get; set; }
        public virtual DbSet<partido> partidoes { get; set; }
    }
}
